### ISSUE TITLE
Node running, und/undcli commands not working in second window

### ISSUE THREAD

**Issue by NLHybrid** [unification-com/testnet#14]
I closed all windows and tried again, it works on the first window and then I can't do anything else once it is running. I am blocked from creating a validator.
Manjaro Linux
Release:	19.0.2
Kernel: Linux 5.5.11-1-MANJARO
Architecture: x86-64

**Comment by Codegnosis** [comment]
Hi,

Thanks for posting the issue. A couple of questions:

1. Has your node fully synced with the network? You'll need to wait for your node to fully sync before running the `create-validator` command
2. Have you checked your firewall is not blocking port 26656?
3. Are setting the correct `--chain-id` flag value? The current chain ID for TestNet is UND-Mainchain-TestNet-v3 - you can find this in the genesis file.
4. Are you getting any error messages?

Cheers

**Comment by NLHybrid** [comment]
I had no problems getting up to the current height. 
I simply get the basic error:
**"bash: undcli: command not found"**
but only in the second terminal window.

**Comment by Codegnosis** [comment]
Sounds like your `go/bin` is not in `$PATH` for your new terminal. If you have updated your bash profile (i.e. `~/.bash_profile` or `~/.profile`) etc. adding your `GOPATH/bin` to `$PATH`, then you probably just need to run `source ~/.bash_profile` in the new terminal window. 

If you run `echo $PATH` and don't see `/home/username/go/bin` (or whatever the path your go/bin is), then you just need to make sure it's in your `$PATH`.

**Comment by NLHybrid** [comment]
Thank you. 
I added **export PATH="$PATH:$HOME/go/bin"** to my /.profile 
then **source ~/.profile** in terminal fixed it. 
The commands are working now and the validator is running on the testnet.
